import type { Metadata } from "next";
import { Lora, Poppins } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QuizFab from "@/components/QuizFab";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Culture Chef",
  description: "Generated by app",
  icons: {
    icon: ["/culture chef1.png"],
    shortcut: ["/culture chef1.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${poppins.variable}`}>
        <Providers>
        <Header /> 
        {children}
        {/* 右下角浮動測驗按鈕 */}
        <QuizFab />
        <Footer /> 
        </Providers>
      </body>
    </html>
  );
}
